version: '3'

services:
  nodejs:
    build:
      context: app/
      dockerfile: Dockerfile
    image: node-mysql
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network

  db:
    build:
      context: db/
      dockerfile: Dockerfile  
    image: mysql
    container_name: db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "9000:9000"
    volumes:
      - dbdata:/var/lib/mysql
#      - ./db/scripts:/docker-entrypoint-initdb.d/sql-scripts/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: